### ISSUE TITLE
TSDKCompletetionBlockTypes.h throwing warnings

### ISSUE THREAD

**Issue by sol43man** [teamsnap/teamsnap-SDK-iOS#146]
The header file has three redundant typedef statements that throw C11 warnings in Xcode:

typedef void (^TSDKSimpleCompletionBlock)(BOOL success, NSError *_Nullable error);
lines 14 and 71

typedef void (^TSDKSimpleCompletionBlock)(BOOL success, NSError *_Nullable error);
line 15 and 78

typedef void (^TSDKCompletionBlock)(BOOL success, BOOL complete, TSDKCollectionJSON *_Nullable objects, NSError *_Nullable error);
line 16 and 75

These lines may be commented out to quell the warnings, and the lines may be removed in the next distribution.

**Comment by SkylerSeamans** [comment]
Resolved in https://github.com/teamsnap/teamsnap-SDK-iOS/pull/269
