### ISSUE TITLE
Nullability annotations for Swift

### ISSUE THREAD

**Issue by SkylerSeamans** [teamsnap/teamsnap-SDK-iOS#21]
Swift consumers would like nullability annotation in headers.

https://developer.apple.com/swift/blog/?id=25

**Comment by larsacus** [comment]
I think this is already completed. @SkylerSeamans confirm?

**Comment by SkylerSeamans** [comment]
I think we're still missing annotations in several files. I haven't audited, recently.

**Comment by larsacus** [comment]
Ok. We definitely have it in most places.
