### ISSUE TITLE
Cannot open my app after authorization

### ISSUE THREAD

**Issue by andrey-lisovskiy** [teamsnap/teamsnap-SDK-iOS#242]
Cannot open my app after authorization.

    func showTeamSnapLoginController() {
        let _ = TSDKTeamSnap.sharedInstance().presentLogin(in: self,
                                                           animated: true,
                                                           clientId: "xxxxxxxxx",
                                                           scope: "read",
                                                           redirectURL: "xxxxx://") {
                                                            debugPrint("LoggedIn")
        }
    }

![img_e6184](https://user-images.githubusercontent.com/7079771/33936732-3a3e799a-e009-11e7-90c8-8f79077c5117.JPG)

**Comment by jrahaim** [comment]
Since you also submitted a help ticket, we'll ask for information there.. and once it's resolved post the solution here. (I suspect your app isn't registered correctly).

**Comment by jrahaim** [comment]
On your `redirectURL` you have to provide a path after the `//` so `myapp://` is invalid.. `myapp://foo` is valid.

**Comment by andrey-lisovskiy** [comment]
Still getting error:
`authorization error
<ActionController::Parameters {"client_id"=>"xxxxxxxxxx", "redirect_uri"=>"xxxx://teamSnap", "scope"=>"read", "response_type"=>"code", "controller"=>"authorizations", "action"=>"new"} permitted: false>`

**Comment by jrahaim** [comment]
We're still looking into it. we'll respond via the support ticket.

**Comment by andrey-lisovskiy** [comment]
I had to add a path after the `myapp://` not only in request, but also in app settings. Thanks!
