### ISSUE TITLE
Pod Install Failure

### ISSUE THREAD

**Issue by xdeleon** [teamsnap/teamsnap-SDK-iOS#268]
> 
> I am trying to install via CocoaPods using the instructions provided here. My podfile is as follows
> ------------------------------------------
> platform :ios, '8.0'
> 
> target 'TeamSnapTest' do
>   use_frameworks!
>   pod 'TeamSnapSDK', :git => 'git@github.com:teamsnap/teamsnap-SDK-iOS.git', :branch => 'master'
> end
> ------------------------------------------
> When I run 'pod install'  get the following error:
> 
> $ pod install
> Analyzing dependencies
> Pre-downloading: `TeamSnapSDK` from `git@github.com:teamsnap/teamsnap-SDK-iOS.git`, branch `master`
> 
> [!] Error installing TeamSnapSDK
> [!] Failed to download 'TeamSnapSDK'.

**Comment by SkylerSeamans** [comment]
Can you try running `git clone git@github.com:teamsnap/teamsnap-SDK-iOS.git` and report back what happens?

**Comment by xdeleon** [comment]
$ git clone git@github.com:teamsnap/teamsnap-SDK-iOS.git
Cloning into 'teamsnap-SDK-iOS'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by SkylerSeamans** [comment]
I believe you need to setup SSH for your Github account.

https://help.github.com/articles/connecting-to-github-with-ssh/

If that doesn't resolve the issue, please let me know!

**Comment by SkylerSeamans** [comment]
Typically most Pods are served via the cocoapods trunk. We currently serve via Github direct (but this may change if more external users start consuming this repo).

What does the content of your podfile look like?

**Comment by xdeleon** [comment]
I posted Podfile contents above already, but here it is again:
cat podfile
platform :ios, '8.0'

target 'TeamSnapTest' do
  use_frameworks!
  pod 'TeamSnapSDK', :git => 'git@github.com:teamsnap/teamsnap-SDK-iOS.git', :branch => 'master'
end

**Comment by SkylerSeamans** [comment]
Try running `pod repo update`

**Comment by SkylerSeamans** [comment]
I was able to install successfully with:

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'Teamsnap' do
pod 'TeamSnapSDK', :git => 'git@github.com:teamsnap/teamsnap-SDK-iOS.git', :branch => 'master'
end

**Comment by larsacus** [comment]
Hey @xdeleon,
In addition to the above, try executing the install with verbose output `pod update --verbose` and get us the result. It sounds like it's related mostly to github, but alternatively in the mean time, we can also try using `:git => 'https://github.com/teamsnap/teamsnap-SDK-iOS.git'` or downloading the zip file and using `:path => '../path-to-local-copy'` to get you up and running.

That should provide us some options while we sort out what the issue could be on our end. Thanks for your patience while we sort this out!

Cheers! 🍻

**Comment by xdeleon** [comment]
K. That seems to have taken care of the issue after I ran:
Downloading dependencies
Installing TeamSnapSDK (3.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

**Comment by SkylerSeamans** [comment]
👍

**Comment by xdeleon** [comment]
This is the verbose install I ran after the above as requested for your troubleshooting:

MacBook-Pro:TeamSnapTest xdeleon$ pod update --verbose
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git -C /Users/xdeleon/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 18, done.        
  remote: Compressing objects: 100% (18/18), done.        
  remote: Total 18 (delta 12), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     6c94877c294..14c1e6118f7  master     -> origin/master
  $ /usr/bin/git -C /Users/xdeleon/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/xdeleon/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 14c1e6118f7 [Add] RNActivityView 0.0.8

CocoaPods 1.5.0 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.0


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-TeamSnapTest`: (``)

Finding Podfile changes
  - TeamSnapSDK

Fetching external sources
-> Pre-downloading: `TeamSnapSDK` from `git@github.com:teamsnap/teamsnap-SDK-iOS.git`, branch `master`
  $ /usr/bin/git ls-remote git@github.com:teamsnap/teamsnap-SDK-iOS.git master
Enter passphrase for key '/Users/xdeleon/.ssh/id_rsa': 
  7487eb82399ea76da38fd345010580efeb3a33e7	refs/heads/master
  > Copying TeamSnapSDK from `/Users/xdeleon/Library/Caches/CocoaPods/Pods/External/TeamSnapSDK/fd33f647b3a542152ff4bc962aaec91f` to
  `Pods/TeamSnapSDK`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  M TeamSnapSDK

Downloading dependencies

-> Installing TeamSnapSDK 3.0 (was 3.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `TeamSnapSDK` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/TeamSnapSDK/Info.plist`
      - Generating module map file at `Pods/Target Support Files/TeamSnapSDK/TeamSnapSDK.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/TeamSnapSDK/TeamSnapSDK-umbrella.h`
    - Installing target `Pods-TeamSnapTest` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-TeamSnapTest/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-TeamSnapTest/Pods-TeamSnapTest.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-TeamSnapTest/Pods-TeamSnapTest-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-TeamSnapTest` (`TeamSnapTest.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`

Sending stats

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
MacBook-Pro:TeamSnapTest xdeleon$
