### ISSUE TITLE
“No such module 'TeamSnapSDK’”

### ISSUE THREAD

**Issue by xdeleon** [teamsnap/teamsnap-SDK-iOS#270]
Having issues building with the SDK.

Steps to reproduce
- Create new swift project called “TeamSnapTest” (Xcode 9.2)
- Create a pod file with the following:

``` ruby
platform :ios, '8.0'

target 'TeamSnapTest' do
  use_frameworks!
  pod 'TeamSnapSDK', :git => 'git@github.com:teamsnap/teamsnap-SDK-iOS.git', :branch => 'master'
end
```

- run ‘pod instal’
- open newly created ‘TeamSnapTest.xcworkspace’
- pod install completes without errors
- go to AppDelegate.swift and add the following line

``` swift
import TeamSnapSDK
```

build app and you get the following error: “No such module 'TeamSnapSDK’”

**Comment by larsacus** [comment]
Which version of Cocoapods are you using for the installation? On my machine using Xcode 9.3 and Cocoapods 1.5 (our internal configuration), I am able to successfully install and link TeamSnapSDK using your above steps. We only recently converted to Xcode 9.3 and cocoapods 1.5, so your above configuration should work properly.

**Comment by xdeleon** [comment]
Cocoapods: 1.4.0, Xcode: 9.2, macOS: 10.12.6. But it appears to be working now. I had created two new clean projects and then added TeamSnap via Cocoapods and it wasn't able to build and I had error above, but now it appears to be working. 

BTW, you should take a pass through the docs on this repo and update. For example:

TSDKTeamSnap.sharedInstance.clientId = myClientID
TSDKTeamSnap.sharedInstance.clientSecret = myClientSecret

Should be:

TSDKTeamSnap.sharedInstance().clientId = myClientID
TSDKTeamSnap.sharedInstance().clientSecret = myClientSecret

There may be other parts that are out of date, but this is as far as I've gotten at the moment. If you need me to log this as a separate issue let me know. Thx

**Comment by larsacus** [comment]
Glad it's working now! I'll go ahead and close this ticket.

As for the documentation issues, we will always entertain PRs improving on anything you see could use improvement (please submit them against the [`develop`](https://github.com/teamsnap/teamsnap-SDK-iOS/tree/develop) branch). For the specific syntax changes you mention, those might have been in one of our previous Swift or Xcode changes that we missed updating our documentation.

If anything else comes up, don't hesitate to reach out!

Cheers! 🍻
