### ISSUE TITLE
Unable to enter numbers or "@" symbol in login view controller

### ISSUE THREAD

**Issue by tachlgithub** [teamsnap/teamsnap-SDK-iOS#275]
Keyboard disappears when clicking numeric keyboard

**Comment by jrahaim** [comment]
That's odd. It's a normal SafariWebView.

Is your default keyboard a 3rd party keyboard? 

do you have a hardware keyboard hooked up? 

is this on a device or simulator?

**Comment by jrahaim** [comment]
Also, can you try the `develop` branch and see if you have the same issue?

**Comment by tachlgithub** [comment]
Is your default keyboard a 3rd party keyboard?
default
do you have a hardware keyboard hooked up?
no
is this on a device or simulator?
device

Restarting phone seems to have fixed the issue, haven't been able to recreate issue since.

**Comment by larsacus** [comment]
Closing this as a restart appears to have fixed it. If anything else comes up please don't hesitate to reach out!
