### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by caleedubya** [teamsnap/teamsnap-SDK-iOS#307]
Hey guys,

I can get the TeamSnap VC auth window to present in my app by using the following:

    @IBAction func teamsnapTouched(_ sender: Any) {
        TSDKTeamSnap.sharedInstance() .presentLogin(in: self, animated: true, clientId: "clientid", scope: "read", redirectURL: "redirectURL") {
            print("VC Presented")     }
    }

But... after I login I can't get it to redirect back to my iOS app. Any suggestions of what to put for callback uri?

Thanks!

Dubya

**Comment by larsacus** [comment]
I apologize for the late response with this. Is your callback URI an `https://` scheme, or is it a custom URL for your application (e.g. `myapp://`)?
